----THIS PROJECT IS DIVIDED INTO TWO PARTS:
---1. DATA CLEANING
---2. EXPLORATORY DATA ANALYSIS AND KEYINSIGHTS


SELECT * FROM amazon_data

SELECT COUNT(*) FROM amazon_data


------------------------------DATA CLEANING------------------
---1. Droping unnesecary Columns---
---2. Changed all values of Ship_city and Ship_state to upper case, since some of the same value is in lower case
---3. Changing Column names
---4. Changing Date Data type to DATE
---5. Creating 3 new Columns-- Year, Month_name, Week_day
---6. Converting INR TO USD
---7. creating new column--- Revenue




---1. Droping unnesecary Columns---

ALTER TABLE amazon_data
DROP COLUMN column1, Style,ASIN,currency,ship_country,Unnamed_22


---2. Changed all values of Ship_city and Ship_state to upper case, since some of the same value is in lower case
SELECT DISTINCT(ship_city) FROM amazon_data

SELECT REPLACE(UPPER(ship_city),'.','') FROM amazon_data

UPDATE amazon_data
SET ship_city = REPLACE(UPPER(ship_city),'.','')


SELECT DISTINCT(ship_state) FROM amazon_data

SELECT REPLACE(UPPER(ship_state),'.','') FROM amazon_data

UPDATE amazon_data
SET ship_state = REPLACE(UPPER(ship_state),'.','')

---3. Changing Column names

EXEC sp_rename 'amazon_data.[index]', 'ind', 'COLUMN';
ALTER TABLE amazon_data
DROP COLUMN ind


EXEC sp_rename 'amazon_data.[Order_ID]', 'Order_id', 'COLUMN';
EXEC sp_rename 'amazon_data.[Sales_Channel]', 'Sales_channel', 'COLUMN';
EXEC sp_rename 'amazon_data.[ship_service_level]', 'Shipping_type', 'COLUMN';
EXEC sp_rename 'amazon_data.[Courier_Status]', 'Courier_status', 'COLUMN';
EXEC sp_rename 'amazon_data.[Qty]', 'Quantity', 'COLUMN';
EXEC sp_rename 'amazon_data.[Amount]', 'Amount_USD', 'COLUMN';
EXEC sp_rename 'amazon_data.[ship_city]', 'Ship_city', 'COLUMN';
EXEC sp_rename 'amazon_data.[ship_state]', 'Ship_state', 'COLUMN';
EXEC sp_rename 'amazon_data.[ship_postal_code]', 'Ship_postal', 'COLUMN';
EXEC sp_rename 'amazon_data.[promotion_ids]', 'Promotion', 'COLUMN';
EXEC sp_rename 'amazon_data.[fulfilled_by]', 'Fulfilled_by', 'COLUMN';




---4. Changing Date Data type  to DATE

UPDATE amazon_data
SET Date = CAST(Date AS DATE)


---5. Creating 3 new Columns-- Year, Month_name, Week_day

SELECT Date, YEAR(Date) as Year,
Month(Date) as Month,
Day(Date) as Day,
DATENAME(MONTH, Date) AS MonthName,
DATENAME(WEEKDAY, Date) AS WeekName
FROM amazon_data


ALTER TABLE amazon_data
ADD Year int,Month_name varchar(50), Week_name varchar(50)

SELECT * FROM amazon_data

UPDATE amazon_data SET Year= YEAR(Date) 
UPDATE amazon_data SET Month_name= DATENAME(MONTH, Date)
UPDATE amazon_data SET Week_name= DATENAME(WEEKDAY, Date)



SELECT DISTINCT(Amount_USD) FROM amazon_data
SELECT DISTINCT(Courier_status) FROM amazon_data
SELECT DISTINCT(Ship_city) FROM amazon_data
SELECT DISTINCT(Ship_state) FROM amazon_data
SELECT DISTINCT(Fulfilled_by) FROM amazon_data

SELECT DISTINCT(Ship_postal) FROM amazon_data

SELECT Amount_USD FROM amazon_data WHERE Amount_USD IS NULL
UPDATE amazon_data SET  Amount_USD = 0 WHERE Amount_USD IS NULL


SELECT Courier_status FROM amazon_data WHERE Courier_status IS NULL
UPDATE amazon_data SET  Courier_status = 'Unkown' WHERE Courier_status IS NULL


SELECT Ship_city FROM amazon_data WHERE Ship_city IS NULL
UPDATE amazon_data SET  Ship_city = 'Unkown' WHERE Ship_city IS NULL


SELECT Ship_state FROM amazon_data WHERE Ship_state IS NULL
UPDATE amazon_data SET  Ship_state = 'Unkown' WHERE Ship_state IS NULL


SELECT Fulfilled_by FROM amazon_data WHERE Fulfilled_by IS NULL
UPDATE amazon_data SET  Fulfilled_by = 'Unkown' WHERE Fulfilled_by IS NULL



SELECT Ship_postal FROM amazon_data WHERE Ship_postal IS NULL
UPDATE amazon_data SET  Ship_postal = 0 WHERE Ship_postal IS NULL

---6. Converting INR TO USD

SELECT ROUND(Amount_USD*.012,2) FROM amazon_data

UPDATE amazon_data
SET Amount_USD= ROUND(Amount_USD*.012,2)


---7. creating new column--- Revenue

SELECT Quantity,Amount_USD, (Quantity*Amount_USD) as Revenue FROM amazon_data 

ALTER TABLE amazon_data
ADD Revenue FLOAT


UPDATE amazon_data SET Revenue= (Quantity*Amount_USD)

SELECT * FROM amazon_data

-------------------------------------------------EXPLORATORY DATA ANALYSIS--------------------
--------------------------------------------------KEYINSIGHTS--------------------------------

---1. What is the total revenue generated over a specific time period?  
--FROM 2022-03-31 TO 2022-06-29 Total Revenue 867306.35
---2. What are the top products by sales and quantity wise? set, Kurta, Western Dress
---3. What are the total Revenue generated by each product for Each Month? set. kurta, western
---4. What is the average order value?  116649 7.78
---5. What are the peak sales periods (week, month, year)? APRIL, SUNDAY, 2022, 2022-05-04
---6. Calculate AOV by Month, Week---MAY, Saturday
---7. What is the average order value of each item? set-10, saree-9.61, wester-9.17
---8. What are the top cities/states/ for sales? City: BENGALURU< HYDRABAD, MUMBAI, state: MAHARASHTRA, KARINATAKA, TELENGANA
---9. Are there any trends in order cancellations?
---most orders cancelled on April
---most orders cancelled if its fulfulled by Amazon compare to marchant
---most orders cancelled by MAHARASHTRA, KARNATAKA state
---most orders cancelled on Trusday and Sunday
---most orders cancelled product set, kurta, western dress
---most orders cancelled who didnt use any promotion compare to promition
---most orders cancelled by B2C compare to B2B
---which shipping metthod tends to get cancelled more? Expedited
---10. What percentage of orders are fulfilled by Amazon vs Merchant?
---mostly by Amazon  where Marchant
---11. How effective are the promotions?
---orders more with promotions and cancels more if it doesnt have promitions
---12. Who generated most revenus?
---amazone more compare to marchant 
---13. Which Shipping metthod is most preffered?
---Expendited
---14. which shipping metthod is mostly used?
---Expedited
---15. which shipping metthod is mostly used preffered by Amazon and merchant?
---Amazon: Expedited, Expedited: Standard




---1. What is the total revenue generated over a specific time period?  
--FROM 2022-03-31 TO 2022-06-29 Total Revenue 867306.35

SELECT MIN(Date) AS START_DATE, MAX(Date) AS END_DATE,ROUND(SUM(Revenue),2) AS TOTAL_REVENUE FROM amazon_data

WHERE Status !='Cancelled'

---2.What are the top products by sales and quantity wise? set, Kurta, Western Dress
SELECT Category, SUM(Quantity) AS Quantity ,ROUND(SUM(Revenue),2) AS TOTAL_REVENUE FROM amazon_data
WHERE Status !='Cancelled' or Quantity>0
GROUP BY Category
ORDER BY TOTAL_REVENUE DESC


---3.What are the total Revenue generated by each product for Each Month? set. kurta, western
SELECT Category,Month_name, SUM(Quantity) AS Quantity ,ROUND(SUM(Revenue),2) AS TOTAL_REVENUE FROM amazon_data
WHERE Status !='Cancelled' or Quantity>0 
GROUP BY  Month_name, Category
ORDER BY TOTAL_REVENUE DESC

---4.What is the average order value?  116649 7.78

SELECT SUM(Quantity) as Total_quantity,  ROUND(SUM(Amount_USD),2) AS Total_amount,   ROUND(AVG(Amount_USD),2) AS AVG_AMOUNT FROM amazon_data
WHERE Status !='Cancelled' or Quantity>0 


---5. What are the peak sales periods (week, month, year)? APRIL, SUNDAY, 2022, 2022-05-04


SELECT TOP 1 Month_name, ROUND(SUM(Revenue),2) AS total_rev FROM amazon_data
WHERE  Status !='Cancelled' or Quantity>0 
GROUP BY  Month_name
ORDER BY SUM(Revenue) DESC

SELECT TOP 1 Week_name, ROUND(SUM(Revenue),2) total_rev FROM amazon_data
WHERE  Status !='Cancelled' or Quantity>0 
GROUP BY  Week_name
ORDER BY SUM(Revenue) DESC

SELECT TOP 1 Year, ROUND(SUM(Revenue),2) total_rev FROM amazon_data
WHERE  Status !='Cancelled' or Quantity>0 
GROUP BY  Year
ORDER BY SUM(Revenue) DESC

SELECT TOP 1 Date, ROUND(SUM(Revenue),2) total_rev FROM amazon_data
WHERE  Status !='Cancelled' or Quantity>0 
GROUP BY  Date
ORDER BY SUM(Revenue) DESC



---6. Calculate AOV by Month, Week---MAY, Saturday

SELECT  Month_name, ROUND(AVG(Revenue),2) AS total_rev FROM amazon_data
WHERE  Status !='Cancelled' or Quantity>0 
GROUP BY  Month_name
ORDER BY AVG(Revenue) DESC

SELECT  Week_name, ROUND(AVG(Revenue),2) total_rev FROM amazon_data
WHERE  Status !='Cancelled' or Quantity>0 
GROUP BY  Week_name
ORDER BY AVG(Revenue) DESC

---7.What is the average order value of each item? set-10, saree-9.61, wester-9.17

SELECT  Category, ROUND(AVG(Amount_USD),2) AS AVG_ORDER FROM amazon_data
WHERE  Status !='Cancelled' or Quantity>0 
GROUP BY  Category
ORDER BY AVG(Amount_USD) DESC


---8.What are the top cities/states/ for sales? City: BENGALURU< HYDRABAD, MUMBAI, state: MAHARASHTRA, KARINATAKA, TELENGANA

SELECT  Ship_city, ROUND(SUM(Revenue),2) AS TOTAL_REV FROM amazon_data
WHERE  Status !='Cancelled' or Quantity>0 
GROUP BY  Ship_city
ORDER BY TOTAL_REV DESC

SELECT  Ship_state, ROUND(SUM(Revenue),2) AS TOTAL_REV FROM amazon_data
WHERE  Status !='Cancelled' or Quantity>0 
GROUP BY  Ship_state
ORDER BY TOTAL_REV DESC

---9.Are there any trends in order cancellations?
---most orders cancelled on April
SELECT  Month_name, COUNT(*) as total_can FROM amazon_data
WHERE  Status ='Cancelled' 
GROUP BY  Month_name
ORDER BY total_can DESC

SELECT * FROM amazon_data

---most orders cancelled if its fulfulled by Amazon compare to marchant
SELECT  Fulfilment, COUNT(*) as total_can FROM amazon_data
WHERE  Status ='Cancelled' 
GROUP BY  Fulfilment
ORDER BY total_can DESC

---most orders cancelled by MAHARASHTRA, KARNATAKA state
SELECT  Ship_state, COUNT(*) as total_can FROM amazon_data
WHERE  Status ='Cancelled' 
GROUP BY  Ship_state
ORDER BY total_can DESC


---most orders cancelled on Trusday and Sunday
SELECT  Week_name, COUNT(*) as total_can FROM amazon_data
WHERE  Status ='Cancelled' 
GROUP BY  Week_name
ORDER BY total_can DESC


---most orders cancelled product set, kurta, western dress
SELECT  Category, COUNT(*) as total_can FROM amazon_data
WHERE  Status ='Cancelled' 
GROUP BY  Category
ORDER BY total_can DESC


---most orders cancelled who didnt use any promotion compare to promition
SELECT  Promotion, COUNT(*) as total_can FROM amazon_data
WHERE  Status ='Cancelled' 
GROUP BY  Promotion
ORDER BY total_can DESC

---most orders cancelled by B2C compare to B2B
SELECT  B2B, COUNT(*) as total_can FROM amazon_data
WHERE  Status ='Cancelled' 
GROUP BY  B2B
ORDER BY total_can DESC

---which shipping metthod tends to get cancelled more?
---Expedited

SELECT  Shipping_type, COUNT(*) as total_can FROM amazon_data
WHERE  Status ='Cancelled' 
GROUP BY  Shipping_type
ORDER BY total_can DESC

--10.What percentage of orders are fulfilled by Amazon vs Merchant?
---mostly by Amazon  where Marchant 
SELECT  Fulfilment, COUNT(*) as total_orders FROM amazon_data 
GROUP BY  Fulfilment
ORDER BY total_orders DESC


SELECT  Fulfilment, COUNT(*) as total_orders FROM amazon_data 
GROUP BY  Fulfilment
ORDER BY total_orders DESC


---11.How effective are the promotions?
---orders more 74.82% with promotions and cancels more if it doesnt have promitions

SELECT  Promotion, COUNT(*) as total_orders FROM amazon_data 
GROUP BY  Promotion
ORDER BY total_orders DESC


--12.Who generated most revenus?
---amazone more compare to marchant 

SELECT  Fulfilment, ROUND(SUM(Revenue),2) as total_orders FROM amazon_data 
GROUP BY  Fulfilment
ORDER BY total_orders DESC


---13. Which Shipping metthod is most preffered?
---Expendited
SELECT  Shipping_type, COUNT(*) as total_orders FROM amazon_data 
GROUP BY  Shipping_type
ORDER BY total_orders DESC


---14. which shipping metthod is mostly used?
---Expedited

SELECT  Shipping_type, COUNT(*) as total_can FROM amazon_data
GROUP BY  Shipping_type
ORDER BY total_can DESC


---15. which shipping metthod is mostly used preffered by Amazon and merchant?
---Amazon: Expedited, Expedited: Standard
SELECT  Fulfilment, Shipping_type, COUNT(*) as total_can FROM amazon_data
GROUP BY  Fulfilment, Shipping_type
ORDER BY total_can DESC